# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Release

on:
  create:
    tags:
    - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 11
      
      - name: Set RELEASE_VERSION
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
  
      - run: npm install vsce -g
      - run: npm install gulp
      - run: npm install
      
      - name: set version
        run: sed -i 's/1.2007.1/'"$RELEASE_VERSION"'/g' ./src/helpers/constants.ts
      - name: git commit locally
        run: git add ./src/helpers/constants.ts
      
      - run: git add ./package.json
      - run: git add ./package-lock.json
      - run: git config --global user.email "devel@argutec.eu"
      - run: git config --global user.name "Argutec"
      - run: git commit -m "Set version"

      - run: gulp build
      - run: gulp package

      - name: publish
        run: vsce publish $RELEASE_VERSION -p ${{ secrets.DEVOPSTOKEN }}

